/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hello.java;

import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
//import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

public class App {
    public static void main(String[] args) {
        //WebDriverManager.chromedriver().setup();
        //final WebDriver webDriver = new ChromeDriver();

        WebDriverManager.firefoxdriver().setup();
        final WebDriver webDriver = new FirefoxDriver();
        webDriver.get("https://www.google.com");

        WebElement element = webDriver.findElement(By.name("q"));
        element.sendKeys("こんにちは、世界");
        element.sendKeys("\n");
    }
}
